### PR TITLE
Problem: Website is missing gentle introduction into ZeroMQ

### PR DESCRIPTION
**Pull request by sappo**
Solution: Start by explaining the ZeroMQ messages and because ZeroMQ has
so many bindings and different implementations make the examples
selectable by using two select boxes: language and library.

@Info: The changes are in draft state and as such are only visible if
hugo is build in draft mode. None of the changes will influence the
appearance of the current live docs.

### CODE REVIEW

**Comment by sappo** [comment]
@zoobab @somdoron thoughts and suggestions are appreciated ;)

**Comment by somdoron** [comment]
Very cool. I'm traveling laptopless this week, so I cannot build in draft mode. Will do next week.

**Comment by somdoron** [comment]
@sappo I like it, the only comment is that we might want it under a different menu than get started.
Maybe Basics?

**Comment by sappo** [comment]
Yes, but I have a different idea in mind.

1. Rename section "Getting started" to "Documentation" so the side menu will look like:

Documentation
* Getting started
* Download
* Messages or ZeroMQ messages
* Socket API
* ... other stuff in the future e.g. zproto, zyre, dafka?

2. Rename "Getting started" on top menu to "Documentation"
3. Replace link to "Download" page in top menu with link to "Community"

**Comment by somdoron** [comment]
Cool, fine by me

**Pull request merged**
