### PR TITLE
add perl language bindings page

### PR DESCRIPTION
**Pull request by calid**

### CODE REVIEW

**Comment by somdoron** [comment]
Thanks!

**Comment by bluca** [comment]
@calid hi - thank you for your work on the Perl bindings! What would you think about moving the repository under the github.com/zeromq org? Is it something you'd be interested in? You'd keep full admin access on the repository of course!

**Comment by calid** [comment]
Absolutely!  I'd be honored

**Comment by bluca** [comment]
Great! I have sent you an invitation to join the org - once done, you can transfer the repository from the bottom of the https://github.com/calid/zmq-ffi/settings page

**Comment by bluca** [comment]
Once it's moved I will add admin permissions to the new perl-maintainers team in the org - you can add invite more peole and add them as co-maintainers, if you wish - all up to you

**Comment by calid** [comment]
ok transferred.  I suppose it should be renamed from the generic zmq-ffi to perlzmq or somesuch?  Whatever you think would be best and most consistent with the other bindings.

**Comment by bluca** [comment]
Great, welcome to the team! You have full admin permissions over the repo now, as does the perl-maintainers group should you wish to name co-maintainers.

The naming is entirely up to you. Given it's already widely used, my feeling would be to keep the name the same, so that existing scripts/forks/users will keep working (github automatically redirects) - but it's your choice.

**Comment by bluca** [comment]
In other words, we do not have a fixed naming convention - you'll find a lot of variety in the repositories in the org.

**Comment by calid** [comment]
Ah okay, so if I rename it will break the auto-redirect functionality?

**Comment by bluca** [comment]
Mmh good question - I do not actually know! Sorry :-)

**Comment by calid** [comment]
We're good!  Redirects are preserved:
https://help.github.com/en/articles/renaming-a-repository

renamed to zeromq/perlzmq

both github.com/calid/zmq-ffi and github.com/zeromq/zmq-ffi are redirecting to the new name.

thanks so much, this is very cool!

**Comment by bluca** [comment]
Perfect!

**Comment by somdoron** [comment]
Amazing, thanks @calid

**Pull request merged**
